2018-01-08 16:21:18 [player_performance] ERROR: 队员详情信息链接，状态码404无数据：http://odf2.worldcurling.co/data/CUR_WWCC2017P/120-game-None.html?cb=1515399677312,保存的不完整信息 {"event_abbr": "CUR_WWCC2017P", "game_session": "24", "event_name": "CPT World Women's Curling Championship 2017", "event_id": "120", "dt_update": "2018-01-08 16:19:12", "game_id": null}
2018-01-08 16:22:50 [player_performance] ERROR: 队员详情信息链接，状态码200无数据：http://odf2.worldcurling.co/data/CUR_WMDCC2017P/122-game-2130.html?cb=1515399748503,保存的不完整信息 {"event_abbr": "CUR_WMDCC2017P", "game_session": "2", "event_name": "World Mixed Doubles Curling Championship 2017", "event_id": "122", "dt_update": "2018-01-08 16:22:09", "game_id": "2130"}
2018-01-08 16:24:43 [player_performance] ERROR: 队员详情信息链接，状态码200无数据：http://odf2.worldcurling.co/data/CUR_WMDCC2017P/122-game-2234.html?cb=1515399859946,保存的不完整信息 {"event_abbr": "CUR_WMDCC2017P", "game_session": "23", "event_name": "World Mixed Doubles Curling Championship 2017", "event_id": "122", "dt_update": "2018-01-08 16:22:09", "game_id": "2234"}
2018-01-08 16:30:51 [player_performance] ERROR: 队员详情信息链接，状态码404无数据：http://odf2.worldcurling.co/data/CUR_WMxCC2017P/125-game-None.html?cb=1515400250058,保存的不完整信息 {"event_abbr": "CUR_WMxCC2017P", "game_session": "2", "event_name": "World Mixed Curling Championship 2017", "event_id": "125", "dt_update": "2018-01-08 16:30:38", "game_id": null}
2018-01-08 16:34:35 [player_performance] ERROR: 队员详情信息链接，状态码200无数据：http://odf2.worldcurling.co/data/CUR_ECCA2017P/127-game-4243.html?cb=1515400453941,保存的不完整信息 {"event_abbr": "CUR_ECCA2017P", "game_session": "10", "event_name": "Le Gruy\\u00e8re AOP European Curling Championships 2017", "event_id": "127", "dt_update": "2018-01-08 16:33:09", "game_id": "4243"}
2018-01-08 16:35:40 [player_performance] ERROR: 队员详情信息链接，状态码404无数据：http://odf2.worldcurling.co/data/CUR_OQE2017P/129-game-4338.html?cb=1515400539833,保存的不完整信息 {"event_abbr": "CUR_OQE2017P", "game_session": "10", "event_name": "Olympic Qualification Event 2017", "event_id": "129", "dt_update": "2018-01-08 16:34:42", "game_id": "4338"}
2018-01-08 16:35:45 [player_performance] ERROR: 队员详情信息链接，状态码404无数据：http://odf2.worldcurling.co/data/CUR_OQE2017P/129-game-4339.html?cb=1515400544129,保存的不完整信息 {"event_abbr": "CUR_OQE2017P", "game_session": "10", "event_name": "Olympic Qualification Event 2017", "event_id": "129", "dt_update": "2018-01-08 16:34:42", "game_id": "4339"}
2018-01-08 16:35:48 [player_performance] ERROR: 队员详情信息链接，状态码404无数据：http://odf2.worldcurling.co/data/CUR_OQE2017P/129-game-4340.html?cb=1515400547479,保存的不完整信息 {"event_abbr": "CUR_OQE2017P", "game_session": "10", "event_name": "Olympic Qualification Event 2017", "event_id": "129", "dt_update": "2018-01-08 16:34:42", "game_id": "4340"}
2018-01-08 16:35:55 [player_performance] ERROR: 队员详情信息链接，状态码404无数据：http://odf2.worldcurling.co/data/CUR_OQE2017P/129-game-4341.html?cb=1515400551326,保存的不完整信息 {"event_abbr": "CUR_OQE2017P", "game_session": "10", "event_name": "Olympic Qualification Event 2017", "event_id": "129", "dt_update": "2018-01-08 16:34:42", "game_id": "4341"}
2018-01-08 16:35:59 [player_performance] ERROR: 队员详情信息链接，状态码404无数据：http://odf2.worldcurling.co/data/CUR_OQE2017P/129-game-4342.html?cb=1515400558171,保存的不完整信息 {"event_abbr": "CUR_OQE2017P", "game_session": "10", "event_name": "Olympic Qualification Event 2017", "event_id": "129", "dt_update": "2018-01-08 16:34:42", "game_id": "4342"}
2018-01-08 16:48:14 [scrapy.core.scraper] ERROR: Error downloading <GET http://http//www.worldcurling.org/events/2017//>
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "c:\python27\lib\site-packages\twisted\python\failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "c:\python27\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\python27\lib\site-packages\twisted\internet\endpoints.py", line 954, in startConnectionAttempts
    "no results for hostname lookup: {}".format(self._hostStr)
DNSLookupError: DNS lookup failed: no results for hostname lookup: http.
2018-01-08 16:50:03 [scrapy.core.scraper] ERROR: Error downloading <GET http://http//www.worldcurling.org/events/2017//>
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "c:\python27\lib\site-packages\twisted\python\failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "c:\python27\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\python27\lib\site-packages\twisted\internet\endpoints.py", line 954, in startConnectionAttempts
    "no results for hostname lookup: {}".format(self._hostStr)
DNSLookupError: DNS lookup failed: no results for hostname lookup: http.
2018-01-08 16:51:41 [scrapy.core.scraper] ERROR: Error downloading <GET http://http//www.worldcurling.org/events/2017/>
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "c:\python27\lib\site-packages\twisted\python\failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "c:\python27\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\python27\lib\site-packages\twisted\internet\endpoints.py", line 954, in startConnectionAttempts
    "no results for hostname lookup: {}".format(self._hostStr)
DNSLookupError: DNS lookup failed: no results for hostname lookup: http.
